apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pipeline.fullname" . }}-config
  labels:
    {{- include "pipeline.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}

