{{- if .Values.secrets.aws.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pipeline.fullname" . }}-aws-secret
  labels:
    {{- include "pipeline.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key-id: {{ .Values.secrets.aws.accessKeyId | quote }}
  secret-access-key: {{ .Values.secrets.aws.secretAccessKey | quote }}
{{- end }}

