# Kustomize staging overlay
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pipeline-staging

resources:
  - ../base

patches:
  - target:
      kind: Deployment
      name: multimodal-pipeline
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/nvidia.com~1gpu
        value: "2"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/nvidia.com~1gpu
        value: "2"

images:
  - name: multimodal-pipeline
    newTag: staging-latest

configMapGenerator:
  - name: multimodal-pipeline-config
    behavior: merge
    literals:
      - LOG_LEVEL=DEBUG
      - ENABLE_PROFILING=true

